# Generated by Django 2.2.4 on 2019-08-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookRecd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('year_b', models.CharField(max_length=100)),
                ('book_p', models.FileField(upload_to='')),
                ('book_url', models.CharField(max_length=250)),
            ],
        ),
    ]
