# Generated by Django 2.1 on 2019-08-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rec', '0003_auto_20190817_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesRecd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=500)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
    ]
